# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, 'release/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-ubuntu-latest:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: Show Toolchain
        run: cat ~/.m2/toolchains.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar target/*.exe staging  
      - uses: actions/upload-artifact@v4
        with:
          name: Package (.jar and .exe)
          path: staging

  build-on-macos-latest:
    
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18.0.2+101
      - name: Show Toolchain
        run: cat ~/.m2/toolchains.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.dmg staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package (.dmg)
          path: staging

  test-against-different-java-versions:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    name: Java ${{ matrix.Java }} sample
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Show Toolchain
        run: cat ~/.m2/toolchains.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir staging && cp target/*.jar target/*.exe staging  
      - uses: actions/upload-artifact@v4
        with:
          name: Package (.jar and .exe)
          path: staging
